version: '3'

services:
  miner:
    image: julian3xl/utopia-miner:latest
    cap_add:
      - IPC_LOCK
    network_mode: bridge
    environment:
      WALLET_ADDR: E8B8118BDD82954C27A56D31FEAFDA455E123EB4DC8F4299C2CA0E7ADB5CC03F
